dist: trusty
sudo: required
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email:
    on_failure: always
    on_success: never
  slack:
    secure: OS2t2tnwZWittCK1C5XpQv41k5zVljZPAmG8DEY1D37RemkyKcNxaXeZwa1/y7qsJZCnPZE4wGbjSE3O3RTbtHbTfb7fBfy3NO/OWjOxszFayS21780U7BSnO9W76FpRyOXZyslsN16gd3Re5FRPvYEJ8w8JvuxhecVpZ6bUUhs+t7i31iQQIpbkat6SN3MmIO+Sb69osP/N4J+dRE40Kiowyp+6pNTlww0cy/uz87R1hnOyy5Izymp2IVAoiR+nAFx6c0Z5l9nYBh5tACQ+2HH+JRuGXndvJatHQeBKw2Ewxxl+NfpG6IGv+Wd5PDnnlotP4ZHUYicx03XjGDuZWiwK01nIn11HhC7UA1ptVvlENXDXWY2EiiXVJgOtNxP+PH5BRivjUEgTBzqS9HQ5fB9HWVQeI4yTN92eN8w/dywek05PYBk04HjjnIYusvnJjzisNjeWQlD8tiQs1oMhsHJO9km1a9TW4/xaD9HDPof2UNaZDEhkXIxRNPtOKQnFajTqA4MWHIr9q8qruXAeRvhcx8gPk06JxatlN/wbQN0EictnZNQbhvCRs9j33Vk7PKNVquths61YYx2nFMKBGT3iHn4HP7Z5iHmfpkYdYdw9SROsLbxR0uxzk8hwQ/cFwEWc6cky25gZu5u8bJu3iIZo+nzcWvjkTsBVcIawlyk=
node_js:
- stable
branches:
  only:
  - master
env:
  global:
  - ENCRYPTION_LABEL: 1787b3626f8e
  - COMMIT_AUTHOR_EMAIL: travis@hcuge.ch
deploy:
  provider: npm
  email: gmer@hcuge.ch
  skip_cleanup: true
  api_key:
    secure: ZTxlrY6bhJdXTVHxu/WzTz3mCCPiE7LfNtXcjv0rDSE121GMyxUq2RmjbXWLwn9s/0cuPr9A20MmOS9+dMJTW81oHGKpMEmFHM4TuANJYMGktWOtq8iFbOKlfnDFZXUyv1+tKyC/eNI7ZRthX6I9e1dQKek8ox4PaZm4VFQ/kOKdXTdD3UQTzF5sScfuRs+f/T64jwVRO/g8rlFM5t38eU95WutgY6oQ+0yKoOGXdJIi3Pp3usBo2+F6jcmwTVIltRtNNzilzebnRSBSHytqouaFz8ypvRRCylqb7OaXF62UZsojLvVJiNluIlOLL0GHKhJJXPpxJC78DPQ6sXb3u54ukFM7la+2rZodLHE6y31TvthErmYih6pba+912SMx8QPaBoUuqUYw/PIfb46n8N5Hbm+9dhigd4Jm3W4NFygh4uAGk3dHLRY1gRKhWyqlcjq6MMiTV+gP6LvSp+1SdYUZjlgT/MEJ5tj+xzhdIPIL1Y8i2fF5HkdhxI9bqXK3yIX+uYWoUjUSbwKAskceBWmruNDC4wgyXLgOsIewutvfGTcq7FbQ2jhVOMETfWUrDBK/+PLbXvNuPaEyOk7pUr2RpqSEWFXnbvjO9auRv+Ois1XvgrsL8cW/SQanYk2PeEfqX0ZHK/xTgAVConcZjoyN2Chm1viYjLvLhg4I160=
  on:
    repo: DSI-HUG/dejajs-resources
    branch: master
after_deploy:
- bash ./scripts/tag.sh
